---
# Domain and network
base_domain: snorp.dev
vps_ip: 216.128.143.17
technitium_ip: 192.168.8.104
proxmox_ip: 192.168.8.187
nas_ip: 192.168.8.204
provisioning_ip: 192.168.8.180
searxng_ip: 192.168.8.139
openclaw_ip: 192.168.8.140
searxng_port: 8888
technitium_lxc_id: 100
provisioning_lxc_id: 101
searxng_lxc_id: 102

openclaw_searxng_url: "http://searx.snorp.dev:8888"

# Cert paths
certbot_cert_name: snorp.dev-0001
certbot_cert_dir: "/etc/letsencrypt/live/{{ certbot_cert_name }}"
cloudflare_ini_path: /root/.cloudflare.ini
proxmox_cert_dir: /etc/pve/local/certs
technitium_pfx_path: /etc/technitium/technitium.pfx

# Technitium
technitium_dns_records:
  - { name: "@",            type: A, value: "{{ vps_ip }}" }
  - { name: "www",          type: A, value: "{{ vps_ip }}" }
  - { name: "*",            type: A, value: "{{ vps_ip }}" }
  - { name: "technitium",   type: A, value: "{{ technitium_ip }}" }
  - { name: "proxmox",      type: A, value: "{{ proxmox_ip }}" }
  - { name: "provisioning", type: A, value: "{{ provisioning_ip }}" }
  - { name: "searx",        type: A, value: "192.168.8.139" }
  - { name: "openclaw",     type: A, value: "192.168.8.140" }
  - { name: "nas",          type: A, value: "{{ nas_ip }}" }

technitium_forwarders:
  - https://cloudflare-dns.com/dns-query
  - https://dns.quad9.net/dns-query
  - https://dns.google/dns-query